export const APP_URL = new URL('http://localhost:3000')
export const AUTH_SERVER_URL = new URL('http://localhost:8080')
export const APP_URL_CROSS_ORIGIN = new URL('http://kjs-app.localhost:3000')
export const AUTH_SERVER_URL_CROSS_ORIGIN = new URL('http://kjs-auth.localhost:8080')
export const ADMIN_USERNAME = 'admin'
export const ADMIN_PASSWORD = 'admin'
export const CLIENT_ID = 'keycloak-js-test-client'
export const AUTHORIZED_USERNAME = 'test-user@localhost'
export const AUTHORIZED_PASSWORD = 'password'
export const UNAUTHORIZED_USERNAME = 'unauthorized'
export const UNAUTHORIZED_PASSWORD = 'password'
